const championData = {
    "266": /* Aatrox */ {"hair": "black", "addOnBeforeHead": {"id": "aatroxBeforeHead", "translationX": -48, "translationY": 70}, "addOnAfterRightArm": {"id": "aatroxRightHand", "handX": 19, "handY": 65, "rotation": 0}},
    "103": /* Ahri */ {"hair": "black", "longHair": true, "addOnBeforeHead": {"id": "ahriBeforeHead", "translationX": -87, "translationY": 40}, "addOnAfterHead": {"id": "ahriHead", "translationX": -17, "translationY": -8}, "addOnAfterRightArm": {"id": "ahriRightHand", "handX": 33, "handY": 70}},
    "84": /* Akali */ {"hair": "black", "longHair": true, "addOnAfterHead": {"id": "akaliHead", "translationX": 6, "translationY": 78}, "addOnAfterLeftArm": {"id": "akaliLeftHand", "handX": 62, "handY": 8, "rotation": 225}, "addOnAfterRightArm": {"id": "akaliRightHand", "handX": 33, "handY": 7, "rotation": 90}},
    "12": /* Alistar */ {"hair": "purple", "addOnAfterHead": {"id": "alistarHead", "translationX": -65, "translationY": -35}},
    "32": /* Amumu */ {"hair": "none", "addOnAfterHead": {"id": "amumuHead", "translationX": -1, "translationY": -1}, "addOnAfterShirt": {"id": "amumuShirt", "translationX": -1, "translationY": 21}, "addOnAfterPants": {"id": "amumuPants", "translationX": -1, "translationY": 2}},
    "34": /* Anivia */ {"hair": "lightBlue"},
    "1": /* Annie */ {"hair": "pink", "longHair": true, "addOnAfterHead": {"id": "annieHead", "translationX": 3, "translationY": -13}, "addOnAfterRightArm": {"id": "annieRightHand", "handX": 42, "handY": 8}},
    "22": /* Ashe */ {"hair": "white", "longHair": true, "addOnAfterRightArm": {"id": "asheRightHand", "handX": 54, "handY": 132}},
    "136": /* Aurelion Sol */ {"hair": "darkPink"},
    "268": /* Azir */ {"hair": "blonde"},
    "432": /* Bard */ {"hair": "none", "hideFace": true, "addOnAfterHead": {"id": "bardHead", "translationX": -15, "translationY": -31}},
    "53": /* Blitzcrank */ {"hair": "blonde"},
    "63": /* Brand */ {"hair": "red"},
    "201": /* Braum */ {"hair": "none"},
    "51": /* Caitlyn */ {"hair": "brown", "longHair": true},
    "164": /* Camille */ {"hair": "white", "longHair": true},
    "69": /* Cassiopeia */ {"hair": "green", "longHair": true},
    "31": /* Cho'Gath */ {"hair": "darkRed"},
    "42": /* Corki */ {"hair": "none", "addOnAfterHead": {"id": "corkiHead", "translationX": -24, "translationY": -34}},
    "122": /* Darius */ {"hair": "black"},
    "131": /* Diana */ {"hair": "white", "longHair": true},
    "36": /* Dr. Mundo */ {"hair": "black"},
    "119": /* Draven */ {"hair": "brown", "longHair": false, "addOnAfterHead": {"id": "dravenHead", "translationX": 14, "translationY": 78, "drawAsHair": true, "hair": "brown"}, "addOnAfterRightArm": {"id": "dravenRightHand", "handX": 101, "handY": 140}, "addOnAfterLeftArm": {"id": "dravenLeftHand", "handX": 29, "handY": 145}},
    "245": /* Ekko */ {"hair": "white"},
    "60": /* Elise */ {"hair": "darkRed", "longHair": true},
    "28": /* Evelynn */ {"hair": "pink", "longHair": true},
    "81": /* Ezreal */ {"hair": "blonde", "addOnAfterHead": {"id": "ezrealHead", "translationX": 0, "translationY": 0}, "addOnAfterRightArm": {"id": "ezrealRightHand", "handX": 18, "handY": 24}},
    "9": /* Fiddlesticks */ {"hair": "tan"},
    "114": /* Fiora */ {"hair": "black", "longHair": true},
    "105": /* Fizz */ {"hair": "lightBlue"},
    "3": /* Galio */ {"hair": "blonde", "addOnBeforeHead": {"id": "galioBeforeHead", "translationX": -48, "translationY": -35}},
    "41": /* Gangplank */ {"hair": "brown"},
    "86": /* Garen */ {"hair": "brown"},
    "150": /* Gnar */ {"hair": "orange", "addOnAfterHead": {"id": "gnarHead", "translationX": 10, "translationY": -40}},
    "79": /* Gragas */ {"hair": "none"},
    "104": /* Graves */ {"hair": "brown"},
    "120": /* Hecarim */ {"hair": "spookyGreen"},
    "74": /* Heimerdinger */ {"hair": "blonde"},
    "420": /* Illaoi */ {"hair": "brown", "longHair": true},
    "39": /* Irelia */ {"hair": "blue", "longHair": true, "addOnBeforeHead": {"id": "ireliaHead", "translationX": -120, "translationY": -130}},
    "427": /* Ivern */ {"hair": "lightGreen"},
    "40": /* Janna */ {"hair": "white", "longHair": true},
    "59": /* Jarvan IV */ {"hair": "black"},
    "24": /* Jax */ {"hair": "darkPink", "addOnAfterLeftArm": {"id": "jaxLeftHand", "handX": 20, "handY": 96, "rotation": 20}},
    "126": /* Jayce */ {"hair": "brown"},
    "202": /* Jhin */ {"hair": "black", "hideFace": true, "addOnAfterHead": {"id": "jhinHead", "translationX": -10, "translationY": 30}},
    "222": /* Jinx */ {"hair": "lightBlue", "longHair": true},
    "145": /* Kai'Sa */ {"hair": "black", "longHair": true},
    "429": /* Kalista */ {"hair": "black", "longHair": true, "addOnBeforeShirt": {"id": "kalistaBeforeShirt", "translationX": 10, "translationY": -25}, "addOnAfterShirt": {"id": "kalistaAfterShirt", "translationX": 0, "translationY": 30}},
    "43": /* Karma */ {"hair": "brown", "longHair": true},
    "30": /* Karthus */ {"hair": "spookyGreen"},
    "38": /* Kassadin */ {"hair": "grey"},
    "55": /* Katarina */ {"hair": "red", "longHair": true},
    "10": /* Kayle */ {"hair": "blonde", "longHair": true},
    "141": /* Kayn */ {"hair": "black"},
    "85": /* Kennen */ {"hair": "brown", "addOnAfterRightArm": {"id": "kennenRightHand", "handX": 59, "handY": 82, "rotation": -15}},
    "121": /* Kha'Zix */ {"hair": "purple"},
    "203": /* Kindred */ {"hair": "white", "longHair": true},
    "240": /* Kled */ {"hair": "white"},
    "96": /* Kog'Maw */ {"hair": "white"},
    "7": /* LeBlanc */ {"hair": "purple", "longHair": true},
    "64": /* Lee Sin */ {"hair": "none", "addOnAfterHead": {"id": "leesinHead", "translationX": 0, "translationY": 37}},
    "89": /* Leona */ {"hair": "orange", "longHair": true},
    "127": /* Lissandra */ {"hair": "white", "longHair": true, "addOnAfterPants": {"id": "lissandraPants", "translationX": -9, "translationY": 7}},
    "236": /* Lucian */ {"hair": "black"},
    "117": /* Lulu */ {"hair": "purple", "longHair": true},
    "99": /* Lux */ {"hair": "blonde", "longHair": true, "addOnAfterLeftArm": {"id": "luxLeftHand", "handX": 32, "handY": 107, "rotation": 30}},
    "54": /* Malphite */ {"hair": "none", "addOnAfterHead": {"id": "malphiteHead", "translationX": -5, "translationY": -67}},
    "90": /* Malzahar */ {"hair": "purple"},
    "57": /* Maokai */ {"hair": "brown"},
    "11": /* Master Yi */ {"hair": "black"},
    "21": /* Miss Fortune */ {"hair": "red", "longHair": true, "addOnAfterRightArm": {"id": "missFortuneRightHand", "handX": 79, "handY": 37}, "addOnAfterLeftArm": {"id": "missFortuneLeftHand", "handX": 38, "handY": 37}},
    "82": /* Mordekaiser */ {"hair": "grey", "addOnAfterLeftArm": {"id": "mordekaiserLeftArm", "handX": 55, "handY": 210, "rotation": 5}},
    "25": /* Morgana */ {"hair": "purple", "longHair": true},
    "267": /* Nami */ {"hair": "blonde", "longHair": true, "addOnAfterRightArm": {"id": "namiRightArm", "handX": 42, "handY": 139, "rotation": -70}},
    "75": /* Nasus */ {"hair": "black"},
    "111": /* Nautilus */ {"hair": "brown"},
    "518": /* Neeko */ {"hair": "blue", "longHair": true},
    "76": /* Nidalee */ {"hair": "black", "longHair": true},
    "56": /* Nocturne */ {"hair": "black", "addOnAfterRightArm": {"id": "nocturneRightArm", "handX": 70, "handY": 40}, "addOnAfterLeftArm": {"id": "nocturneLeftArm", "handX": 10, "handY": 40}},
    "20": /* Nunu */ {"hair": "black"},
    "2": /* Olaf */ {"hair": "orange"},
    "61": /* Orianna */ {"hair": "blonde", "longHair": true, "addOnAfterHead": {"id": "oriannaHead", "translationX": 80, "translationY": -20}},
    "516": /* Ornn */ {"hair": "darkRed"},
    "80": /* Pantheon */ {"hair": "black", "addOnAfterLeftArm": {"id": "pantheonRightHand", "handX": 67, "handY": 67}},
    "78": /* Poppy */ {"hair": "white", "longHair": true, "addOnAfterRightArm": {"id": "poppyRightHand", "handX": 40, "handY": 59, "rotation": 165}},
    "555": /* Pyke */ {"hair": "none", "addOnAfterHead": {"id": "pykeHead", "translationX": 4, "translationY": 78}},
    "133": /* Quinn */ {"hair": "brown", "longHair": true},
    "497": /* Rakan */ {"hair": "white"},
    "33": /* Rammus */ {"hair": "none", "addOnAfterHead": {"id": "rammusHead", "translationX": -3, "translationY": -42}},
    "421": /* Rek'Sai */ {"hair": "darkPink"},
    "58": /* Renekton */ {"hair": "tan"},
    "107": /* Rengar */ {"hair": "white"},
    "92": /* Riven */ {"hair": "white", "addOnAfterLeftArm": {"id": "rivenLeftHand", "handX": 17, "handY": 241, "rotation": 95}},
    "68": /* Rumble */ {"hair": "lightBlue"},
    "13": /* Ryze */ {"hair": "none", "addOnBeforeHead": {"id": "ryzeBeforeHead", "translationX": -5, "translationY": 75}},
    "113": /* Sejuani */ {"hair": "white", "longHair": true},
    "35": /* Shaco */ {"hair": "darkRed"},
    "98": /* Shen */ {"hair": "blue"},
    "102": /* Shyvana */ {"hair": "darkRed", "longHair": true},
    "27": /* Singed */ {"hair": "none"},
    "14": /* Sion */ {"hair": "none"},
    "15": /* Sivir */ {"hair": "black", "longHair": true, "addOnAfterLeftArm": {"id": "sivirLeftHand", "handX": 67, "handY": 60}},
    "72": /* Skarner */ {"hair": "purple"},
    "37": /* Sona */ {"hair": "lightBlue", "longHair": true},
    "16": /* Soraka */ {"hair": "white", "longHair": true},
    "50": /* Swain */ {"hair": "grey"},
    "517": /* Sylas */ {"hair": "black"},
    "134": /* Syndra */ {"hair": "white", "longHair": true, "addOnAfterHead": {"id": "syndraHead", "translationX": -55, "translationY": -75}},
    "223": /* Tahm Kench */ {"hair": "none"},
    "163": /* Taliyah */ {"hair": "brown"},
    "91": /* Talon */ {"hair": "blue"},
    "44": /* Taric */ {"hair": "brown", "longHair": true},
    "17": /* Teemo */ {"hair": "none", "addOnAfterHead": {"id": "teemoHead", "translationX": -15, "translationY": -33}},
    "412": /* Thresh */ {"hair": "spookyGreen"},
    "18": /* Tristana */ {"hair": "white"},
    "48": /* Trundle */ {"hair": "darkPink", "addOnAfterLeftArm": {"id": "trundleLeftHand", "handX": 65, "handY": 186, "rotation": 20}},
    "23": /* Tryndamere */ {"hair": "black"},
    "4": /* Twisted Fate */ {"hair": "black"},
    "29": /* Twitch */ {"hair": "grey"},
    "77": /* Udyr */ {"hair": "brown"},
    "6": /* Urgot */ {"hair": "none"},
    "110": /* Varus */ {"hair": "white"},
    "67": /* Vayne */ {"hair": "black", "longHair": true},
    "45": /* Veigar */ {"hair": "purple"},
    "161": /* Vel'Koz */ {"hair": "purple"},
    "254": /* Vi */ {"hair": "pink", "longHair": true},
    "112": /* Viktor */ {"hair": "brown"},
    "8": /* Vladimir */ {"hair": "white"},
    "106": /* Volibear */ {"hair": "white"},
    "19": /* Warwick */ {"hair": "grey"},
    "62": /* Wukong */ {"hair": "brown"},
    "498": /* Xayah */ {"hair": "darkRed", "longHair": true},
    "101": /* Xerath */ {"hair": "black"},
    "5": /* Xin Zhao */ {"hair": "black"},
    "157": /* Yasuo */ {"hair": "black"},
    "83": /* Yorick */ {"hair": "blue"}, 
    "154": /* Zac */ {"hair": "none", "addOnAfterHead": {"id": "zacHead", "translationX": 1, "translationY": -76}},
    "238": /* Zed */ {"hair": "grey"},
    "115": /* Ziggs */ {"hair": "brown", "addOnAfterRightArm": {"id": "ziggsHand", "handX": 50, "handY": 89}, "addOnAfterLeftArm": {"id": "ziggsHand", "handX": 20, "handY": 89}},
    "26": /* Zilean */ {"hair": "lightBlue"},
    "142": /* Zoe */ {"hair": "orange", "longHair": true},
    "143": /* Zyra */ {"hair": "red", "longHair": true},
};