const championData = {
    "266": /* Aatrox */ {"hair": "black", "addOnBeforeHead": {"id": "aatroxBeforeHead", "translationX": -48, "translationY": 70}, "addOnAfterRightArm": {"id": "aatroxRightHand", "handX": 19, "handY": 65, "rotation": 0}},
    "103": /* Ahri */ {"hair": "black", "longHair": true, "addOnBeforeHead": {"id": "ahriBeforeHead", "translationX": -87, "translationY": 40}, "addOnAfterHead": {"id": "ahriHead", "translationX": -17, "translationY": -8}, "addOnAfterRightArm": {"id": "ahriRightHand", "handX": 33, "handY": 70}},
    "84": /* Akali */ {"hair": "black", "longHair": true, "addOnAfterHead": {"id": "akaliHead", "translationX": 6, "translationY": 78}, "addOnAfterLeftArm": {"id": "akaliLeftHand", "handX": 62, "handY": 8, "rotation": 225}, "addOnAfterRightArm": {"id": "akaliRightHand", "handX": 33, "handY": 7, "rotation": 90}},
    "12": /* Alistar */ {"hair": "purple", "addOnAfterHead": {"id": "alistarHead", "translationX": -65, "translationY": -35}},
    "32": /* Amumu */ {"hair": "none", "addOnAfterHead": {"id": "amumuHead", "translationX": -1, "translationY": -1}, "addOnAfterShirt": {"id": "amumuShirt", "translationX": -1, "translationY": 21}, "addOnAfterPants": {"id": "amumuPants", "translationX": -1, "translationY": 2}},
    "1": /* Annie */ {"hair": "pink", "longHair": true, "addOnAfterHead": {"id": "annieHead", "translationX": 3, "translationY": -13}, "addOnAfterRightArm": {"id": "annieRightHand", "handX": 42, "handY": 8}},
    "22": /* Ashe */ {"hair": "white", "longHair": true, "addOnAfterRightArm": {"id": "asheRightHand", "handX": 54, "handY": 132}},
    "432": /* Bard */ {"hair": "none", "hideFace": true, "addOnAfterHead": {"id": "bardHead", "translationX": -15, "translationY": -31}},
    "119": /* Draven */ {"hair": "brown", "longHair": false, "addOnAfterHead": {"id": "dravenHead", "translationX": 14, "translationY": 78, "drawAsHair": true, "hair": "brown"}, "addOnAfterRightArm": {"id": "dravenRightHand", "handX": 101, "handY": 140}, "addOnAfterLeftArm": {"id": "dravenLeftHand", "handX": 29, "handY": 145}},
    "92": /* Riven */ {"hair": "white", "addOnAfterLeftArm": {"id": "rivenLeftHand", "handX": 17, "handY": 241, "rotation": 95}},
    "13": /* Ryze */ {"hair": "none", "addOnBeforeHead": {"id": "ryzeBeforeHead", "translationX": -5, "translationY": 75}},
    "15": /* Sivir */ {"hair": "black", "longHair": true, "addOnAfterLeftArm": {"id": "sivirLeftHand", "handX": 67, "handY": 60}},
    "17": /* Teemo */ {"hair": "none", "addOnAfterHead": {"id": "teemoHead", "translationX": -15, "translationY": -33}},
    "48": /* Trundle */ {"hair": "darkPink", "addOnAfterLeftArm": {"id": "trundleLeftHand", "handX": 65, "handY": 186, "rotation": 20}},
    "141": /* Zac */ {"hair": "none", "addOnAfterHead": {"id": "zacHead", "translationX": 1, "translationY": -76}},
    "115": /* Ziggs */ {"hair": "brown", "addOnAfterRightArm": {"id": "ziggsHand", "handX": 50, "handY": 89}, "addOnAfterLeftArm": {"id": "ziggsHand", "handX": 20, "handY": 89}},
};